/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;
import controlador.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelos.*;
import tda.Lista;
/**
 *
 * @author n04615
 */
public class InterfazMoverExpediente extends javax.swing.JFrame {
    private GestionDependencia objGestionDependencia;
    private int id;
    private String nombre;
    private GestionPersonal objGestionUsuarios;

    public InterfazMoverExpediente() {
        initComponents();   
    }
    public InterfazMoverExpediente(int id, String nombre,GestionDependencia objGestionDependencia, GestionPersonal objGestionUsuarios){
        initComponents();
        this.id=id;
        this.nombre=nombre;        
        this.objGestionDependencia=objGestionDependencia;
        this.objGestionUsuarios=objGestionUsuarios;
        
        DefaultComboBoxModel<String> comboboxModel= new DefaultComboBoxModel<>();
        Lista<Dependencia> dependencia = objGestionDependencia.getDependencias();
        int n=dependencia.longitud();
       
        for (int i = 1; i <= n; i++) {
            Dependencia depen=dependencia.iesimo(i);
            if(depen != null){
                comboboxModel.addElement(depen.getNombre());
            }
            else {
                System.err.println("Elemento nulo encontrado en la posición: " + i);
            }
        }
        combito2.setModel(comboboxModel);
    }
    
    public Dependencia retornarDependencia() {
        String dependenciaNombre = this.nombre;
        Dependencia dependenciaSeleccionada = null;
            for (int i = 1; i <= objGestionDependencia.getDependencias().longitud(); i++) {
                Dependencia dep = objGestionDependencia.getDependencias().iesimo(i);
                if (dep.getNombre().equals(dependenciaNombre)) {
                    dependenciaSeleccionada = dep;
                    break;
                }
            }
        return dependenciaSeleccionada;      
    }    
    public void agregarDependenciaOrigen() {
        Dependencia dependenciaSeleccionada = retornarDependencia();
        Expediente expediente = dependenciaSeleccionada.removerExpediente(this.id);
        expediente.agregarDependenciaRecorrida(dependenciaSeleccionada.getNombre());
        System.out.println("la dependencia que se agrego fue: " + dependenciaSeleccionada.getNombre());
        dependenciaSeleccionada.agregarExpediente(expediente);
    }

    public void mover(){
        String dependenciaDestino = (String)combito2.getSelectedItem();
        String dependenciaOrigen = this.nombre;  
        agregarDependenciaOrigen();
        boolean verificar= objGestionDependencia.moverExpediente(this.id, dependenciaOrigen, dependenciaDestino);
        if(verificar==true){
            JOptionPane.showMessageDialog(this,"Movimiento exitoso");
        }else{
            JOptionPane.showMessageDialog(this,"Movimiento fallido");
        }
    }
    

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combito2 = new javax.swing.JComboBox<>();
        botonMover = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("SELECCIONE DEPENDENCIA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("A MOVER EXPEDIENTE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        combito2.setBackground(new java.awt.Color(204, 204, 204));
        combito2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        combito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combito2ActionPerformed(evt);
            }
        });
        jPanel1.add(combito2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 190, -1));

        botonMover.setBackground(new java.awt.Color(255, 51, 0));
        botonMover.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        botonMover.setForeground(new java.awt.Color(255, 255, 255));
        botonMover.setText("Mover");
        botonMover.setBorderPainted(false);
        botonMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMoverActionPerformed(evt);
            }
        });
        jPanel1.add(botonMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, 30));

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Menú");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/InterfaszMoverExpedienteFONDO.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combito2ActionPerformed
           
    }//GEN-LAST:event_combito2ActionPerformed

    private void botonMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMoverActionPerformed
        mover();   
    }//GEN-LAST:event_botonMoverActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        InterfazAdministrador form = new InterfazAdministrador(objGestionDependencia,objGestionUsuarios);
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMoverExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMoverExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMoverExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMoverExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMoverExpediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMover;
    private javax.swing.JComboBox<String> combito2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
