/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;
import modelos.*;
import tda.*;
import controlador.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Alonso
 */
public class InterfazVerDatosExpediente extends javax.swing.JFrame {
    
    private GestionDependencia objGestionDependencia;
    private GestionPersonal objGestionUsuarios;
    private Expediente expediente;
    private String nombreDependencia;
    private Dependencia dependenciaSeleccionada;
    private DefaultTableModel modeloTabla1;
    
    public InterfazVerDatosExpediente() {
        initComponents();
        modeloTabla1=new DefaultTableModel();
        modeloTabla1.addColumn("Dependencias recorridas");   
        tablaDependenciasRecorridas.setModel(modeloTabla1);
    }
    public InterfazVerDatosExpediente(String nombreDependencia, GestionDependencia objGestionDependencia, GestionPersonal objGestionUsuarios, Expediente expediente){
        initComponents();
        this.objGestionDependencia=objGestionDependencia;
        this.objGestionUsuarios=objGestionUsuarios;
        this.expediente=expediente;
        this.dependenciaSeleccionada = retornarDependencia(nombreDependencia);
        rellenarDatos(expediente);
        modeloTabla1=new DefaultTableModel();
        modeloTabla1.addColumn("Dependencias recorridas");   
        tablaDependenciasRecorridas.setModel(modeloTabla1);
        cargarDependenciasRecorridas();
        
    }
    public void rellenarDatos(Expediente expediente){
        txtNombre.setText(expediente.getInteresado().getNombre());
        txtNombre.setEditable(false);
        
        txtDni.setText(String.valueOf(expediente.getInteresado().getDni()));
        txtDni.setEditable(false);
        
        txtEmail.setText(expediente.getInteresado().getEmail());
        txtEmail.setEditable(false);
        
        txtTelefono.setText(String.valueOf(expediente.getInteresado().getTelefono()));
        txtTelefono.setEditable(false);
        
        txtInfo.setText(expediente.getDocumento());
        txtInfo.setEditable(false);
        
        txtPrioridad.setText(expediente.getPrioridad2().getPrioridad());
        txtPrioridad.setEditable(false);
        
        txtEstado.setText(expediente.getEstado());
        txtEstado.setEditable(false); 
        
        txtDependenciActual.setText(expediente.getDependenciaActual());
        
        this.dependenciaSeleccionada.agregarExpediente(expediente);
        
    }
    
    public Dependencia retornarDependencia(String nombreDependencia) {
        String dependenciaNombre = nombreDependencia;
        Dependencia dependenciaSeleccionada = null;
            for (int i = 1; i <= objGestionDependencia.getDependencias().longitud(); i++) {
                Dependencia dep = objGestionDependencia.getDependencias().iesimo(i);
                if (dep.getNombre().equals(dependenciaNombre)) {
                    dependenciaSeleccionada = dep;
                    break;
                }
            }
        return dependenciaSeleccionada;      
    }

    public void cargarDependenciasRecorridas() {
    Lista<String> dependenciasRecorridas = expediente.getDependenciasRecorridas();
    int n = dependenciasRecorridas.longitud();
    for (int i = 1; i <= n; i++) {
        String nombreDependenciasRecorridas = dependenciasRecorridas.iesimo(i);
        if (nombreDependenciasRecorridas != null) {
            String[] fila = new String[1];
            fila[0] = nombreDependenciasRecorridas;
            modeloTabla1.addRow(fila);
        } else {
            System.err.println("Elemento nulo encontrado en la posición: " + i);
        }
    }
}

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDependenciasRecorridas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtInfo = new javax.swing.JTextField();
        txtDependenciActual = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtPrioridad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("DATOS DEL EXPEDIENTE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 24, -1, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 160, -1));

        tablaDependenciasRecorridas.setBackground(new java.awt.Color(204, 204, 204));
        tablaDependenciasRecorridas.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        tablaDependenciasRecorridas.setForeground(new java.awt.Color(255, 51, 0));
        tablaDependenciasRecorridas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaDependenciasRecorridas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 160, 250));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 61, 60, 30));

        txtNombre.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 100, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel5.setText("Información ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel11.setText("Dependencia actual");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setText("Teléfono");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 131, -1, 30));

        txtInfo.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        getContentPane().add(txtInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 100, -1));

        txtDependenciActual.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        getContentPane().add(txtDependenciActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 100, -1));

        txtTelefono.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, -1));

        txtPrioridad.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        getContentPane().add(txtPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 100, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel7.setText("Prioridad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        txtEstado.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 100, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel8.setText("Estado");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 100, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 60, 30));

        txtDni.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 100, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setText("DNI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECURSOS/InterfazVerDatosExpedinteFONDO.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        InterfazAdministrador form = new InterfazAdministrador(objGestionDependencia,objGestionUsuarios);
        form.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazVerDatosExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazVerDatosExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazVerDatosExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazVerDatosExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazVerDatosExpediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaDependenciasRecorridas;
    private javax.swing.JTextField txtDependenciActual;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtInfo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrioridad;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
